// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pimpOilDischarge.proto

package dg.model;

public final class PimpOilDischarge {
  private PimpOilDischarge() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *卸油操作类型
   * </pre>
   *
   * Protobuf enum {@code dg.model.OilDischargeEventType}
   */
  public enum OilDischargeEventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>Oil_Discharge_Event_Type_Unknown = 0;</code>
     */
    Oil_Discharge_Event_Type_Unknown(0),
    /**
     * <pre>
     *开始卸油
     * </pre>
     *
     * <code>Oil_Discharge_Event_Type_Begin = 1;</code>
     */
    Oil_Discharge_Event_Type_Begin(1),
    /**
     * <pre>
     *结束卸油
     * </pre>
     *
     * <code>Oil_Discharge_Event_Type_End = 2;</code>
     */
    Oil_Discharge_Event_Type_End(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>Oil_Discharge_Event_Type_Unknown = 0;</code>
     */
    public static final int Oil_Discharge_Event_Type_Unknown_VALUE = 0;
    /**
     * <pre>
     *开始卸油
     * </pre>
     *
     * <code>Oil_Discharge_Event_Type_Begin = 1;</code>
     */
    public static final int Oil_Discharge_Event_Type_Begin_VALUE = 1;
    /**
     * <pre>
     *结束卸油
     * </pre>
     *
     * <code>Oil_Discharge_Event_Type_End = 2;</code>
     */
    public static final int Oil_Discharge_Event_Type_End_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OilDischargeEventType valueOf(int value) {
      return forNumber(value);
    }

    public static OilDischargeEventType forNumber(int value) {
      switch (value) {
        case 0: return Oil_Discharge_Event_Type_Unknown;
        case 1: return Oil_Discharge_Event_Type_Begin;
        case 2: return Oil_Discharge_Event_Type_End;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OilDischargeEventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OilDischargeEventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OilDischargeEventType>() {
            public OilDischargeEventType findValueByNumber(int number) {
              return OilDischargeEventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dg.model.PimpOilDischarge.getDescriptor().getEnumTypes().get(0);
    }

    private static final OilDischargeEventType[] VALUES = values();

    public static OilDischargeEventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OilDischargeEventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dg.model.OilDischargeEventType)
  }

  public interface OilDischargeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dg.model.OilDischarge)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    java.lang.String getOilStationId();
    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOilStationIdBytes();

    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    java.lang.String getEventId();
    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    com.google.protobuf.ByteString
        getEventIdBytes();

    /**
     * <pre>
     *事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     *事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     *卸油操作类型
     * </pre>
     *
     * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
     */
    int getEventTypeValue();
    /**
     * <pre>
     *卸油操作类型
     * </pre>
     *
     * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
     */
    dg.model.PimpOilDischarge.OilDischargeEventType getEventType();

    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */
    int getAdditionalInfosCount();
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */
    boolean containsAdditionalInfos(
        java.lang.String key);
    /**
     * Use {@link #getAdditionalInfosMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalInfos();
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalInfosMap();
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    java.lang.String getAdditionalInfosOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    java.lang.String getAdditionalInfosOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *卸油接收对象
   * </pre>
   *
   * Protobuf type {@code dg.model.OilDischarge}
   */
  public  static final class OilDischarge extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dg.model.OilDischarge)
      OilDischargeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OilDischarge.newBuilder() to construct.
    private OilDischarge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OilDischarge() {
      oilStationId_ = "";
      eventId_ = "";
      timestamp_ = "";
      eventType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OilDischarge(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              oilStationId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              eventId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              eventType_ = rawValue;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                additionalInfos_ = com.google.protobuf.MapField.newMapField(
                    AdditionalInfosDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              additionalInfos__ = input.readMessage(
                  AdditionalInfosDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              additionalInfos_.getMutableMap().put(
                  additionalInfos__.getKey(), additionalInfos__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischarge_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAdditionalInfos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischarge_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dg.model.PimpOilDischarge.OilDischarge.class, dg.model.PimpOilDischarge.OilDischarge.Builder.class);
    }

    private int bitField0_;
    public static final int OILSTATIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object oilStationId_;
    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    public java.lang.String getOilStationId() {
      java.lang.Object ref = oilStationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oilStationId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOilStationIdBytes() {
      java.lang.Object ref = oilStationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oilStationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object eventId_;
    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     *事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 4;
    private int eventType_;
    /**
     * <pre>
     *卸油操作类型
     * </pre>
     *
     * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
     */
    public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <pre>
     *卸油操作类型
     * </pre>
     *
     * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
     */
    public dg.model.PimpOilDischarge.OilDischargeEventType getEventType() {
      @SuppressWarnings("deprecation")
      dg.model.PimpOilDischarge.OilDischargeEventType result = dg.model.PimpOilDischarge.OilDischargeEventType.valueOf(eventType_);
      return result == null ? dg.model.PimpOilDischarge.OilDischargeEventType.UNRECOGNIZED : result;
    }

    public static final int ADDITIONALINFOS_FIELD_NUMBER = 5;
    private static final class AdditionalInfosDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  dg.model.PimpOilDischarge.internal_static_dg_model_OilDischarge_AdditionalInfosEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> additionalInfos_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAdditionalInfos() {
      if (additionalInfos_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AdditionalInfosDefaultEntryHolder.defaultEntry);
      }
      return additionalInfos_;
    }

    public int getAdditionalInfosCount() {
      return internalGetAdditionalInfos().getMap().size();
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public boolean containsAdditionalInfos(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAdditionalInfos().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAdditionalInfosMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfos() {
      return getAdditionalInfosMap();
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfosMap() {
      return internalGetAdditionalInfos().getMap();
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public java.lang.String getAdditionalInfosOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalInfos().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public java.lang.String getAdditionalInfosOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalInfos().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOilStationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oilStationId_);
      }
      if (!getEventIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      if (eventType_ != dg.model.PimpOilDischarge.OilDischargeEventType.Oil_Discharge_Event_Type_Unknown.getNumber()) {
        output.writeEnum(4, eventType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAdditionalInfos(),
          AdditionalInfosDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOilStationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oilStationId_);
      }
      if (!getEventIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      if (eventType_ != dg.model.PimpOilDischarge.OilDischargeEventType.Oil_Discharge_Event_Type_Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, eventType_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAdditionalInfos().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        additionalInfos__ = AdditionalInfosDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, additionalInfos__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dg.model.PimpOilDischarge.OilDischarge)) {
        return super.equals(obj);
      }
      dg.model.PimpOilDischarge.OilDischarge other = (dg.model.PimpOilDischarge.OilDischarge) obj;

      boolean result = true;
      result = result && getOilStationId()
          .equals(other.getOilStationId());
      result = result && getEventId()
          .equals(other.getEventId());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && eventType_ == other.eventType_;
      result = result && internalGetAdditionalInfos().equals(
          other.internalGetAdditionalInfos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OILSTATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getOilStationId().hashCode();
      hash = (37 * hash) + EVENTID_FIELD_NUMBER;
      hash = (53 * hash) + getEventId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
      if (!internalGetAdditionalInfos().getMap().isEmpty()) {
        hash = (37 * hash) + ADDITIONALINFOS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAdditionalInfos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dg.model.PimpOilDischarge.OilDischarge parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dg.model.PimpOilDischarge.OilDischarge prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *卸油接收对象
     * </pre>
     *
     * Protobuf type {@code dg.model.OilDischarge}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dg.model.OilDischarge)
        dg.model.PimpOilDischarge.OilDischargeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischarge_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAdditionalInfos();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAdditionalInfos();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischarge_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dg.model.PimpOilDischarge.OilDischarge.class, dg.model.PimpOilDischarge.OilDischarge.Builder.class);
      }

      // Construct using dg.model.PimpOilDischarge.OilDischarge.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        oilStationId_ = "";

        eventId_ = "";

        timestamp_ = "";

        eventType_ = 0;

        internalGetMutableAdditionalInfos().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischarge_descriptor;
      }

      @java.lang.Override
      public dg.model.PimpOilDischarge.OilDischarge getDefaultInstanceForType() {
        return dg.model.PimpOilDischarge.OilDischarge.getDefaultInstance();
      }

      @java.lang.Override
      public dg.model.PimpOilDischarge.OilDischarge build() {
        dg.model.PimpOilDischarge.OilDischarge result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dg.model.PimpOilDischarge.OilDischarge buildPartial() {
        dg.model.PimpOilDischarge.OilDischarge result = new dg.model.PimpOilDischarge.OilDischarge(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.oilStationId_ = oilStationId_;
        result.eventId_ = eventId_;
        result.timestamp_ = timestamp_;
        result.eventType_ = eventType_;
        result.additionalInfos_ = internalGetAdditionalInfos();
        result.additionalInfos_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dg.model.PimpOilDischarge.OilDischarge) {
          return mergeFrom((dg.model.PimpOilDischarge.OilDischarge)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dg.model.PimpOilDischarge.OilDischarge other) {
        if (other == dg.model.PimpOilDischarge.OilDischarge.getDefaultInstance()) return this;
        if (!other.getOilStationId().isEmpty()) {
          oilStationId_ = other.oilStationId_;
          onChanged();
        }
        if (!other.getEventId().isEmpty()) {
          eventId_ = other.eventId_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.eventType_ != 0) {
          setEventTypeValue(other.getEventTypeValue());
        }
        internalGetMutableAdditionalInfos().mergeFrom(
            other.internalGetAdditionalInfos());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dg.model.PimpOilDischarge.OilDischarge parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dg.model.PimpOilDischarge.OilDischarge) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object oilStationId_ = "";
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public java.lang.String getOilStationId() {
        java.lang.Object ref = oilStationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oilStationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOilStationIdBytes() {
        java.lang.Object ref = oilStationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oilStationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public Builder setOilStationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oilStationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public Builder clearOilStationId() {
        
        oilStationId_ = getDefaultInstance().getOilStationId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public Builder setOilStationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oilStationId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventId_ = "";
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public java.lang.String getEventId() {
        java.lang.Object ref = eventId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEventIdBytes() {
        java.lang.Object ref = eventId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public Builder setEventId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public Builder clearEventId() {
        
        eventId_ = getDefaultInstance().getEventId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public Builder setEventIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       *事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <pre>
       *卸油操作类型
       * </pre>
       *
       * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
       */
      public int getEventTypeValue() {
        return eventType_;
      }
      /**
       * <pre>
       *卸油操作类型
       * </pre>
       *
       * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
       */
      public Builder setEventTypeValue(int value) {
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卸油操作类型
       * </pre>
       *
       * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
       */
      public dg.model.PimpOilDischarge.OilDischargeEventType getEventType() {
        @SuppressWarnings("deprecation")
        dg.model.PimpOilDischarge.OilDischargeEventType result = dg.model.PimpOilDischarge.OilDischargeEventType.valueOf(eventType_);
        return result == null ? dg.model.PimpOilDischarge.OilDischargeEventType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *卸油操作类型
       * </pre>
       *
       * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
       */
      public Builder setEventType(dg.model.PimpOilDischarge.OilDischargeEventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卸油操作类型
       * </pre>
       *
       * <code>.dg.model.OilDischargeEventType EventType = 4;</code>
       */
      public Builder clearEventType() {
        
        eventType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> additionalInfos_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAdditionalInfos() {
        if (additionalInfos_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AdditionalInfosDefaultEntryHolder.defaultEntry);
        }
        return additionalInfos_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAdditionalInfos() {
        onChanged();;
        if (additionalInfos_ == null) {
          additionalInfos_ = com.google.protobuf.MapField.newMapField(
              AdditionalInfosDefaultEntryHolder.defaultEntry);
        }
        if (!additionalInfos_.isMutable()) {
          additionalInfos_ = additionalInfos_.copy();
        }
        return additionalInfos_;
      }

      public int getAdditionalInfosCount() {
        return internalGetAdditionalInfos().getMap().size();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public boolean containsAdditionalInfos(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAdditionalInfos().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAdditionalInfosMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfos() {
        return getAdditionalInfosMap();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfosMap() {
        return internalGetAdditionalInfos().getMap();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public java.lang.String getAdditionalInfosOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalInfos().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public java.lang.String getAdditionalInfosOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalInfos().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAdditionalInfos() {
        internalGetMutableAdditionalInfos().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public Builder removeAdditionalInfos(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalInfos().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAdditionalInfos() {
        return internalGetMutableAdditionalInfos().getMutableMap();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */
      public Builder putAdditionalInfos(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalInfos().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public Builder putAllAdditionalInfos(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAdditionalInfos().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dg.model.OilDischarge)
    }

    // @@protoc_insertion_point(class_scope:dg.model.OilDischarge)
    private static final dg.model.PimpOilDischarge.OilDischarge DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dg.model.PimpOilDischarge.OilDischarge();
    }

    public static dg.model.PimpOilDischarge.OilDischarge getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OilDischarge>
        PARSER = new com.google.protobuf.AbstractParser<OilDischarge>() {
      @java.lang.Override
      public OilDischarge parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OilDischarge(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OilDischarge> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OilDischarge> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dg.model.PimpOilDischarge.OilDischarge getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OilDischargePublishOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dg.model.OilDischargePublish)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    java.lang.String getOilStationId();
    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOilStationIdBytes();

    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    java.lang.String getEventId();
    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    com.google.protobuf.ByteString
        getEventIdBytes();

    /**
     * <pre>
     *结束事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     *结束事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     *人脸特征图片链接
     * </pre>
     *
     * <code>string FaceImageUrl = 4;</code>
     */
    java.lang.String getFaceImageUrl();
    /**
     * <pre>
     *人脸特征图片链接
     * </pre>
     *
     * <code>string FaceImageUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getFaceImageUrlBytes();

    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */
    int getAdditionalInfosCount();
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */
    boolean containsAdditionalInfos(
        java.lang.String key);
    /**
     * Use {@link #getAdditionalInfosMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalInfos();
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalInfosMap();
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    java.lang.String getAdditionalInfosOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    java.lang.String getAdditionalInfosOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *卸油推送对象
   * </pre>
   *
   * Protobuf type {@code dg.model.OilDischargePublish}
   */
  public  static final class OilDischargePublish extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dg.model.OilDischargePublish)
      OilDischargePublishOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OilDischargePublish.newBuilder() to construct.
    private OilDischargePublish(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OilDischargePublish() {
      oilStationId_ = "";
      eventId_ = "";
      timestamp_ = "";
      faceImageUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OilDischargePublish(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              oilStationId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              eventId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              timestamp_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              faceImageUrl_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                additionalInfos_ = com.google.protobuf.MapField.newMapField(
                    AdditionalInfosDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              additionalInfos__ = input.readMessage(
                  AdditionalInfosDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              additionalInfos_.getMutableMap().put(
                  additionalInfos__.getKey(), additionalInfos__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischargePublish_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAdditionalInfos();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischargePublish_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dg.model.PimpOilDischarge.OilDischargePublish.class, dg.model.PimpOilDischarge.OilDischargePublish.Builder.class);
    }

    private int bitField0_;
    public static final int OILSTATIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object oilStationId_;
    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    public java.lang.String getOilStationId() {
      java.lang.Object ref = oilStationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oilStationId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *加油站ID
     * </pre>
     *
     * <code>string OilStationId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOilStationIdBytes() {
      java.lang.Object ref = oilStationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oilStationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object eventId_;
    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *卸油事件ID
     * </pre>
     *
     * <code>string EventId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     *结束事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *结束事件时间
     * </pre>
     *
     * <code>string Timestamp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FACEIMAGEURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object faceImageUrl_;
    /**
     * <pre>
     *人脸特征图片链接
     * </pre>
     *
     * <code>string FaceImageUrl = 4;</code>
     */
    public java.lang.String getFaceImageUrl() {
      java.lang.Object ref = faceImageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faceImageUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *人脸特征图片链接
     * </pre>
     *
     * <code>string FaceImageUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFaceImageUrlBytes() {
      java.lang.Object ref = faceImageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faceImageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDITIONALINFOS_FIELD_NUMBER = 5;
    private static final class AdditionalInfosDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  dg.model.PimpOilDischarge.internal_static_dg_model_OilDischargePublish_AdditionalInfosEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> additionalInfos_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAdditionalInfos() {
      if (additionalInfos_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AdditionalInfosDefaultEntryHolder.defaultEntry);
      }
      return additionalInfos_;
    }

    public int getAdditionalInfosCount() {
      return internalGetAdditionalInfos().getMap().size();
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public boolean containsAdditionalInfos(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAdditionalInfos().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAdditionalInfosMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfos() {
      return getAdditionalInfosMap();
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfosMap() {
      return internalGetAdditionalInfos().getMap();
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public java.lang.String getAdditionalInfosOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalInfos().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *附加信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
     */

    public java.lang.String getAdditionalInfosOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalInfos().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOilStationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, oilStationId_);
      }
      if (!getEventIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      if (!getFaceImageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, faceImageUrl_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAdditionalInfos(),
          AdditionalInfosDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOilStationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, oilStationId_);
      }
      if (!getEventIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventId_);
      }
      if (!getTimestampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      if (!getFaceImageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, faceImageUrl_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAdditionalInfos().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        additionalInfos__ = AdditionalInfosDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, additionalInfos__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dg.model.PimpOilDischarge.OilDischargePublish)) {
        return super.equals(obj);
      }
      dg.model.PimpOilDischarge.OilDischargePublish other = (dg.model.PimpOilDischarge.OilDischargePublish) obj;

      boolean result = true;
      result = result && getOilStationId()
          .equals(other.getOilStationId());
      result = result && getEventId()
          .equals(other.getEventId());
      result = result && getTimestamp()
          .equals(other.getTimestamp());
      result = result && getFaceImageUrl()
          .equals(other.getFaceImageUrl());
      result = result && internalGetAdditionalInfos().equals(
          other.internalGetAdditionalInfos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OILSTATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getOilStationId().hashCode();
      hash = (37 * hash) + EVENTID_FIELD_NUMBER;
      hash = (53 * hash) + getEventId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      hash = (37 * hash) + FACEIMAGEURL_FIELD_NUMBER;
      hash = (53 * hash) + getFaceImageUrl().hashCode();
      if (!internalGetAdditionalInfos().getMap().isEmpty()) {
        hash = (37 * hash) + ADDITIONALINFOS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAdditionalInfos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dg.model.PimpOilDischarge.OilDischargePublish parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dg.model.PimpOilDischarge.OilDischargePublish prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *卸油推送对象
     * </pre>
     *
     * Protobuf type {@code dg.model.OilDischargePublish}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dg.model.OilDischargePublish)
        dg.model.PimpOilDischarge.OilDischargePublishOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischargePublish_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAdditionalInfos();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAdditionalInfos();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischargePublish_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dg.model.PimpOilDischarge.OilDischargePublish.class, dg.model.PimpOilDischarge.OilDischargePublish.Builder.class);
      }

      // Construct using dg.model.PimpOilDischarge.OilDischargePublish.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        oilStationId_ = "";

        eventId_ = "";

        timestamp_ = "";

        faceImageUrl_ = "";

        internalGetMutableAdditionalInfos().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dg.model.PimpOilDischarge.internal_static_dg_model_OilDischargePublish_descriptor;
      }

      @java.lang.Override
      public dg.model.PimpOilDischarge.OilDischargePublish getDefaultInstanceForType() {
        return dg.model.PimpOilDischarge.OilDischargePublish.getDefaultInstance();
      }

      @java.lang.Override
      public dg.model.PimpOilDischarge.OilDischargePublish build() {
        dg.model.PimpOilDischarge.OilDischargePublish result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dg.model.PimpOilDischarge.OilDischargePublish buildPartial() {
        dg.model.PimpOilDischarge.OilDischargePublish result = new dg.model.PimpOilDischarge.OilDischargePublish(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.oilStationId_ = oilStationId_;
        result.eventId_ = eventId_;
        result.timestamp_ = timestamp_;
        result.faceImageUrl_ = faceImageUrl_;
        result.additionalInfos_ = internalGetAdditionalInfos();
        result.additionalInfos_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dg.model.PimpOilDischarge.OilDischargePublish) {
          return mergeFrom((dg.model.PimpOilDischarge.OilDischargePublish)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dg.model.PimpOilDischarge.OilDischargePublish other) {
        if (other == dg.model.PimpOilDischarge.OilDischargePublish.getDefaultInstance()) return this;
        if (!other.getOilStationId().isEmpty()) {
          oilStationId_ = other.oilStationId_;
          onChanged();
        }
        if (!other.getEventId().isEmpty()) {
          eventId_ = other.eventId_;
          onChanged();
        }
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (!other.getFaceImageUrl().isEmpty()) {
          faceImageUrl_ = other.faceImageUrl_;
          onChanged();
        }
        internalGetMutableAdditionalInfos().mergeFrom(
            other.internalGetAdditionalInfos());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dg.model.PimpOilDischarge.OilDischargePublish parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dg.model.PimpOilDischarge.OilDischargePublish) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object oilStationId_ = "";
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public java.lang.String getOilStationId() {
        java.lang.Object ref = oilStationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          oilStationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOilStationIdBytes() {
        java.lang.Object ref = oilStationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          oilStationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public Builder setOilStationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        oilStationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public Builder clearOilStationId() {
        
        oilStationId_ = getDefaultInstance().getOilStationId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *加油站ID
       * </pre>
       *
       * <code>string OilStationId = 1;</code>
       */
      public Builder setOilStationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        oilStationId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventId_ = "";
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public java.lang.String getEventId() {
        java.lang.Object ref = eventId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEventIdBytes() {
        java.lang.Object ref = eventId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public Builder setEventId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public Builder clearEventId() {
        
        eventId_ = getDefaultInstance().getEventId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *卸油事件ID
       * </pre>
       *
       * <code>string EventId = 2;</code>
       */
      public Builder setEventIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       *结束事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *结束事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *结束事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结束事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结束事件时间
       * </pre>
       *
       * <code>string Timestamp = 3;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object faceImageUrl_ = "";
      /**
       * <pre>
       *人脸特征图片链接
       * </pre>
       *
       * <code>string FaceImageUrl = 4;</code>
       */
      public java.lang.String getFaceImageUrl() {
        java.lang.Object ref = faceImageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faceImageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *人脸特征图片链接
       * </pre>
       *
       * <code>string FaceImageUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFaceImageUrlBytes() {
        java.lang.Object ref = faceImageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faceImageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *人脸特征图片链接
       * </pre>
       *
       * <code>string FaceImageUrl = 4;</code>
       */
      public Builder setFaceImageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faceImageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *人脸特征图片链接
       * </pre>
       *
       * <code>string FaceImageUrl = 4;</code>
       */
      public Builder clearFaceImageUrl() {
        
        faceImageUrl_ = getDefaultInstance().getFaceImageUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *人脸特征图片链接
       * </pre>
       *
       * <code>string FaceImageUrl = 4;</code>
       */
      public Builder setFaceImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        faceImageUrl_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> additionalInfos_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAdditionalInfos() {
        if (additionalInfos_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AdditionalInfosDefaultEntryHolder.defaultEntry);
        }
        return additionalInfos_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAdditionalInfos() {
        onChanged();;
        if (additionalInfos_ == null) {
          additionalInfos_ = com.google.protobuf.MapField.newMapField(
              AdditionalInfosDefaultEntryHolder.defaultEntry);
        }
        if (!additionalInfos_.isMutable()) {
          additionalInfos_ = additionalInfos_.copy();
        }
        return additionalInfos_;
      }

      public int getAdditionalInfosCount() {
        return internalGetAdditionalInfos().getMap().size();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public boolean containsAdditionalInfos(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAdditionalInfos().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAdditionalInfosMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfos() {
        return getAdditionalInfosMap();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAdditionalInfosMap() {
        return internalGetAdditionalInfos().getMap();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public java.lang.String getAdditionalInfosOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalInfos().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public java.lang.String getAdditionalInfosOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalInfos().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAdditionalInfos() {
        internalGetMutableAdditionalInfos().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public Builder removeAdditionalInfos(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalInfos().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAdditionalInfos() {
        return internalGetMutableAdditionalInfos().getMutableMap();
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */
      public Builder putAdditionalInfos(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalInfos().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *附加信息
       * </pre>
       *
       * <code>map&lt;string, string&gt; AdditionalInfos = 5;</code>
       */

      public Builder putAllAdditionalInfos(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAdditionalInfos().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dg.model.OilDischargePublish)
    }

    // @@protoc_insertion_point(class_scope:dg.model.OilDischargePublish)
    private static final dg.model.PimpOilDischarge.OilDischargePublish DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dg.model.PimpOilDischarge.OilDischargePublish();
    }

    public static dg.model.PimpOilDischarge.OilDischargePublish getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OilDischargePublish>
        PARSER = new com.google.protobuf.AbstractParser<OilDischargePublish>() {
      @java.lang.Override
      public OilDischargePublish parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OilDischargePublish(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OilDischargePublish> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OilDischargePublish> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dg.model.PimpOilDischarge.OilDischargePublish getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dg_model_OilDischarge_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dg_model_OilDischarge_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dg_model_OilDischarge_AdditionalInfosEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dg_model_OilDischarge_AdditionalInfosEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dg_model_OilDischargePublish_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dg_model_OilDischargePublish_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dg_model_OilDischargePublish_AdditionalInfosEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dg_model_OilDischargePublish_AdditionalInfosEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026pimpOilDischarge.proto\022\010dg.model\"\372\001\n\014O" +
      "ilDischarge\022\024\n\014OilStationId\030\001 \001(\t\022\017\n\007Eve" +
      "ntId\030\002 \001(\t\022\021\n\tTimestamp\030\003 \001(\t\0222\n\tEventTy" +
      "pe\030\004 \001(\0162\037.dg.model.OilDischargeEventTyp" +
      "e\022D\n\017AdditionalInfos\030\005 \003(\0132+.dg.model.Oi" +
      "lDischarge.AdditionalInfosEntry\0326\n\024Addit" +
      "ionalInfosEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 " +
      "\001(\t:\0028\001\"\352\001\n\023OilDischargePublish\022\024\n\014OilSt" +
      "ationId\030\001 \001(\t\022\017\n\007EventId\030\002 \001(\t\022\021\n\tTimest" +
      "amp\030\003 \001(\t\022\024\n\014FaceImageUrl\030\004 \001(\t\022K\n\017Addit" +
      "ionalInfos\030\005 \003(\01322.dg.model.OilDischarge" +
      "Publish.AdditionalInfosEntry\0326\n\024Addition" +
      "alInfosEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001*\203\001\n\025OilDischargeEventType\022$\n Oil_Di" +
      "scharge_Event_Type_Unknown\020\000\022\"\n\036Oil_Disc" +
      "harge_Event_Type_Begin\020\001\022 \n\034Oil_Discharg" +
      "e_Event_Type_End\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dg_model_OilDischarge_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dg_model_OilDischarge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dg_model_OilDischarge_descriptor,
        new java.lang.String[] { "OilStationId", "EventId", "Timestamp", "EventType", "AdditionalInfos", });
    internal_static_dg_model_OilDischarge_AdditionalInfosEntry_descriptor =
      internal_static_dg_model_OilDischarge_descriptor.getNestedTypes().get(0);
    internal_static_dg_model_OilDischarge_AdditionalInfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dg_model_OilDischarge_AdditionalInfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_dg_model_OilDischargePublish_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dg_model_OilDischargePublish_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dg_model_OilDischargePublish_descriptor,
        new java.lang.String[] { "OilStationId", "EventId", "Timestamp", "FaceImageUrl", "AdditionalInfos", });
    internal_static_dg_model_OilDischargePublish_AdditionalInfosEntry_descriptor =
      internal_static_dg_model_OilDischargePublish_descriptor.getNestedTypes().get(0);
    internal_static_dg_model_OilDischargePublish_AdditionalInfosEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dg_model_OilDischargePublish_AdditionalInfosEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
