// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pimpObject.proto

package dg.model;

public final class PimpObject {
  private PimpObject() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dg.model.ObjectType}
   */
  public enum ObjectType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>Object_Type_Unknown = 0;</code>
     */
    Object_Type_Unknown(0),
    /**
     * <pre>
     *提挂枪对象
     * </pre>
     *
     * <code>Object_Type_Oil_Event = 1;</code>
     */
    Object_Type_Oil_Event(1),
    /**
     * <pre>
     *油品交易对象
     * </pre>
     *
     * <code>Object_Type_Oil_Trade = 2;</code>
     */
    Object_Type_Oil_Trade(2),
    /**
     * <pre>
     *非油品交易对象
     * </pre>
     *
     * <code>Object_Type_Non_Oil_Trade = 3;</code>
     */
    Object_Type_Non_Oil_Trade(3),
    /**
     * <pre>
     *开票
     * </pre>
     *
     * <code>Object_Type_Ticket_Open = 4;</code>
     */
    Object_Type_Ticket_Open(4),
    /**
     * <pre>
     *扫卷
     * </pre>
     *
     * <code>Object_Type_Coupon_Used = 5;</code>
     */
    Object_Type_Coupon_Used(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未知
     * </pre>
     *
     * <code>Object_Type_Unknown = 0;</code>
     */
    public static final int Object_Type_Unknown_VALUE = 0;
    /**
     * <pre>
     *提挂枪对象
     * </pre>
     *
     * <code>Object_Type_Oil_Event = 1;</code>
     */
    public static final int Object_Type_Oil_Event_VALUE = 1;
    /**
     * <pre>
     *油品交易对象
     * </pre>
     *
     * <code>Object_Type_Oil_Trade = 2;</code>
     */
    public static final int Object_Type_Oil_Trade_VALUE = 2;
    /**
     * <pre>
     *非油品交易对象
     * </pre>
     *
     * <code>Object_Type_Non_Oil_Trade = 3;</code>
     */
    public static final int Object_Type_Non_Oil_Trade_VALUE = 3;
    /**
     * <pre>
     *开票
     * </pre>
     *
     * <code>Object_Type_Ticket_Open = 4;</code>
     */
    public static final int Object_Type_Ticket_Open_VALUE = 4;
    /**
     * <pre>
     *扫卷
     * </pre>
     *
     * <code>Object_Type_Coupon_Used = 5;</code>
     */
    public static final int Object_Type_Coupon_Used_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ObjectType valueOf(int value) {
      return forNumber(value);
    }

    public static ObjectType forNumber(int value) {
      switch (value) {
        case 0: return Object_Type_Unknown;
        case 1: return Object_Type_Oil_Event;
        case 2: return Object_Type_Oil_Trade;
        case 3: return Object_Type_Non_Oil_Trade;
        case 4: return Object_Type_Ticket_Open;
        case 5: return Object_Type_Coupon_Used;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ObjectType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ObjectType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ObjectType>() {
            public ObjectType findValueByNumber(int number) {
              return ObjectType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PimpObject.getDescriptor().getEnumTypes().get(0);
    }

    private static final ObjectType[] VALUES = values();

    public static ObjectType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ObjectType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dg.model.ObjectType)
  }

  public interface ObjectPublishOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dg.model.ObjectPublish)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.dg.model.ObjectType ObjectType = 1;</code>
     */
    int getObjectTypeValue();
    /**
     * <code>.dg.model.ObjectType ObjectType = 1;</code>
     */
    PimpObject.ObjectType getObjectType();

    /**
     * <pre>
     *proto序列化
     * </pre>
     *
     * <code>bytes BinData = 2;</code>
     */
    com.google.protobuf.ByteString getBinData();
  }
  /**
   * Protobuf type {@code dg.model.ObjectPublish}
   */
  public  static final class ObjectPublish extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dg.model.ObjectPublish)
      ObjectPublishOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ObjectPublish.newBuilder() to construct.
    private ObjectPublish(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ObjectPublish() {
      objectType_ = 0;
      binData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ObjectPublish(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              objectType_ = rawValue;
              break;
            }
            case 18: {

              binData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PimpObject.internal_static_dg_model_ObjectPublish_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PimpObject.internal_static_dg_model_ObjectPublish_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PimpObject.ObjectPublish.class, PimpObject.ObjectPublish.Builder.class);
    }

    public static final int OBJECTTYPE_FIELD_NUMBER = 1;
    private int objectType_;
    /**
     * <code>.dg.model.ObjectType ObjectType = 1;</code>
     */
    public int getObjectTypeValue() {
      return objectType_;
    }
    /**
     * <code>.dg.model.ObjectType ObjectType = 1;</code>
     */
    public PimpObject.ObjectType getObjectType() {
      @SuppressWarnings("deprecation")
      PimpObject.ObjectType result = PimpObject.ObjectType.valueOf(objectType_);
      return result == null ? PimpObject.ObjectType.UNRECOGNIZED : result;
    }

    public static final int BINDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString binData_;
    /**
     * <pre>
     *proto序列化
     * </pre>
     *
     * <code>bytes BinData = 2;</code>
     */
    public com.google.protobuf.ByteString getBinData() {
      return binData_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (objectType_ != PimpObject.ObjectType.Object_Type_Unknown.getNumber()) {
        output.writeEnum(1, objectType_);
      }
      if (!binData_.isEmpty()) {
        output.writeBytes(2, binData_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (objectType_ != PimpObject.ObjectType.Object_Type_Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, objectType_);
      }
      if (!binData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, binData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PimpObject.ObjectPublish)) {
        return super.equals(obj);
      }
      PimpObject.ObjectPublish other = (PimpObject.ObjectPublish) obj;

      boolean result = true;
      result = result && objectType_ == other.objectType_;
      result = result && getBinData()
          .equals(other.getBinData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OBJECTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + objectType_;
      hash = (37 * hash) + BINDATA_FIELD_NUMBER;
      hash = (53 * hash) + getBinData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PimpObject.ObjectPublish parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PimpObject.ObjectPublish parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PimpObject.ObjectPublish parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PimpObject.ObjectPublish parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PimpObject.ObjectPublish parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PimpObject.ObjectPublish parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PimpObject.ObjectPublish parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PimpObject.ObjectPublish parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PimpObject.ObjectPublish parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PimpObject.ObjectPublish parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PimpObject.ObjectPublish parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PimpObject.ObjectPublish parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PimpObject.ObjectPublish prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dg.model.ObjectPublish}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dg.model.ObjectPublish)
        PimpObject.ObjectPublishOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PimpObject.internal_static_dg_model_ObjectPublish_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PimpObject.internal_static_dg_model_ObjectPublish_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PimpObject.ObjectPublish.class, PimpObject.ObjectPublish.Builder.class);
      }

      // Construct using dg.model.PimpObject.ObjectPublish.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        objectType_ = 0;

        binData_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PimpObject.internal_static_dg_model_ObjectPublish_descriptor;
      }

      @Override
      public PimpObject.ObjectPublish getDefaultInstanceForType() {
        return PimpObject.ObjectPublish.getDefaultInstance();
      }

      @Override
      public PimpObject.ObjectPublish build() {
        PimpObject.ObjectPublish result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PimpObject.ObjectPublish buildPartial() {
        PimpObject.ObjectPublish result = new PimpObject.ObjectPublish(this);
        result.objectType_ = objectType_;
        result.binData_ = binData_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PimpObject.ObjectPublish) {
          return mergeFrom((PimpObject.ObjectPublish)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PimpObject.ObjectPublish other) {
        if (other == PimpObject.ObjectPublish.getDefaultInstance()) return this;
        if (other.objectType_ != 0) {
          setObjectTypeValue(other.getObjectTypeValue());
        }
        if (other.getBinData() != com.google.protobuf.ByteString.EMPTY) {
          setBinData(other.getBinData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PimpObject.ObjectPublish parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PimpObject.ObjectPublish) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int objectType_ = 0;
      /**
       * <code>.dg.model.ObjectType ObjectType = 1;</code>
       */
      public int getObjectTypeValue() {
        return objectType_;
      }
      /**
       * <code>.dg.model.ObjectType ObjectType = 1;</code>
       */
      public Builder setObjectTypeValue(int value) {
        objectType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.dg.model.ObjectType ObjectType = 1;</code>
       */
      public PimpObject.ObjectType getObjectType() {
        @SuppressWarnings("deprecation")
        PimpObject.ObjectType result = PimpObject.ObjectType.valueOf(objectType_);
        return result == null ? PimpObject.ObjectType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dg.model.ObjectType ObjectType = 1;</code>
       */
      public Builder setObjectType(PimpObject.ObjectType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        objectType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dg.model.ObjectType ObjectType = 1;</code>
       */
      public Builder clearObjectType() {

        objectType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString binData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *proto序列化
       * </pre>
       *
       * <code>bytes BinData = 2;</code>
       */
      public com.google.protobuf.ByteString getBinData() {
        return binData_;
      }
      /**
       * <pre>
       *proto序列化
       * </pre>
       *
       * <code>bytes BinData = 2;</code>
       */
      public Builder setBinData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        binData_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *proto序列化
       * </pre>
       *
       * <code>bytes BinData = 2;</code>
       */
      public Builder clearBinData() {

        binData_ = getDefaultInstance().getBinData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dg.model.ObjectPublish)
    }

    // @@protoc_insertion_point(class_scope:dg.model.ObjectPublish)
    private static final PimpObject.ObjectPublish DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PimpObject.ObjectPublish();
    }

    public static PimpObject.ObjectPublish getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ObjectPublish>
        PARSER = new com.google.protobuf.AbstractParser<ObjectPublish>() {
      @Override
      public ObjectPublish parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObjectPublish(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ObjectPublish> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ObjectPublish> getParserForType() {
      return PARSER;
    }

    @Override
    public PimpObject.ObjectPublish getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dg_model_ObjectPublish_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dg_model_ObjectPublish_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020pimpObject.proto\022\010dg.model\"J\n\rObjectPu" +
      "blish\022(\n\nObjectType\030\001 \001(\0162\024.dg.model.Obj" +
      "ectType\022\017\n\007BinData\030\002 \001(\014*\264\001\n\nObjectType\022" +
      "\027\n\023Object_Type_Unknown\020\000\022\031\n\025Object_Type_" +
      "Oil_Event\020\001\022\031\n\025Object_Type_Oil_Trade\020\002\022\035" +
      "\n\031Object_Type_Non_Oil_Trade\020\003\022\033\n\027Object_" +
      "Type_Ticket_Open\020\004\022\033\n\027Object_Type_Coupon" +
      "_Used\020\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dg_model_ObjectPublish_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dg_model_ObjectPublish_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dg_model_ObjectPublish_descriptor,
        new String[] { "ObjectType", "BinData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
